### ISSUE TITLE
Feature: Update Sections in Settings Page and minor features

### ISSUE THREAD

**Issue by jayam04** [jayam04/simple-new-tab#19]
Currently  Settings Page is divided into 4 Sections, we want to merge them into one section. We also want to add a real-time preview on the right side. We also want to add more options.

**Tasks**
- [ ] Support Page
    - [ ] Add notice that donations will be used to support news houses and individual news reporters in India who are dauntless when asking hard questions to the Government.
    - [ ] Ask users to support by reviews app (not necessarily positive review, but just helpful such that extension can improve).
- [ ] Add Gradient support for Main Page (newtab.html)
